//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Fifth Dimension Warriors.rc
//
#define IDR_MENU1                       101
#define IDB_STRSCREENMASK               107
#define IDD_MODEBOX                     109
#define IDB_BATTLEARENA1                115
#define IDB_BATTLEARENA2                116
#define IDB_BATTLEARENA3                117
#define IDB_BATTLEARENAMASK             118
#define IDB_BARMASK                     119
#define IDB_BAR                         120
#define IDB_NAME_1C                     154
#define IDB_NAME_1D                     155
#define IDB_NAME_1A                     156
#define IDB_NAME_1B                     157
#define IDB_NAME_2C                     158
#define IDB_NAME_2D                     159
#define IDB_NAME_2A                     160
#define IDB_NAME_2B                     161
#define IDB_NAME_1MASK                  165
#define IDB_NAME_2MASK                  166
#define IDB_QUATTRO_1AMASK              168
#define IDB_QUATTRO_1A                  169
#define IDB_QUATTRO_1BMASK              170
#define IDB_QUATTRO_1B                  171
#define IDB_QUATTRO_1CMASK              172
#define IDB_QUATTRO_1C                  173
#define IDB_QUATTRO_1DMASK              174
#define IDB_QUATTRO_1D                  175
#define IDB_QUATTRO_2AMASK              176
#define IDB_QUATTRO_2A                  177
#define IDB_QUATTRO_2BMASK              178
#define IDB_QUATTRO_2B                  179
#define IDB_QUATTRO_2CMASK              180
#define IDB_QUATTRO_2C                  181
#define IDB_QUATTRO_2DMASK              182
#define IDB_QUATTRO_2D                  183
#define IDB_QUATTRO_3AMASK              184
#define IDB_QUATTRO_3A                  185
#define IDB_QUATTRO_3BMASK              186
#define IDB_QUATTRO_3B                  187
#define IDB_QUATTRO_3CMASK              188
#define IDB_QUATTRO_3C                  189
#define IDB_QUATTRO_3DMASK              190
#define IDB_QUATTRO_3D                  191
#define IDB_QUATTRO_4AMASK              192
#define IDB_QUATTRO_4A                  193
#define IDB_QUATTRO_4BMASK              194
#define IDB_QUATTRO_4B                  195
#define IDB_QUATTRO_4CMASK              196
#define IDB_QUATTRO_4C                  197
#define IDB_QUATTRO_4DMASK              198
#define IDB_QUATTRO_4D                  199
#define IDB_DIMITRI_1AMASK              200
#define IDB_DIMITRI_1A                  201
#define IDB_DIMITRI_1BMASK              202
#define IDB_DIMITRI_1B                  203
#define IDB_DIMITRI_1CMASK              204
#define IDB_DIMITRI_1C                  205
#define IDB_DIMITRI_1DMASK              206
#define IDB_DIMITRI_1D                  207
#define IDB_DIMITRI_2AMASK              208
#define IDB_DIMITRI_2A                  209
#define IDB_DIMITRI_2BMASK              210
#define IDB_DIMITRI_2B                  211
#define IDB_DIMITRI_2CMASK              212
#define IDB_DIMITRI_2C                  213
#define IDB_DIMITRI_2DMASK              214
#define IDB_DIMITRI_2D                  215
#define IDB_DIMITRI_3AMASK              216
#define IDB_DIMITRI_3A                  217
#define IDB_DIMITRI_3BMASK              218
#define IDB_DIMITRI_3B                  219
#define IDB_DIMITRI_3CMASK              220
#define IDB_DIMITRI_3C                  221
#define IDB_DIMITRI_3DMASK              222
#define IDB_DIMITRI_3D                  223
#define IDB_DIMITRI_4AMASK              224
#define IDB_DIMITRI_4A                  225
#define IDB_DIMITRI_4BMASK              226
#define IDB_DIMITRI_4B                  227
#define IDB_DIMITRI_4CMASK              228
#define IDB_DIMITRI_4C                  229
#define IDB_DIMITRI_4DMASK              230
#define IDB_DIMITRI_4D                  231
#define IDB_LIUJIAO_1AMASK              232
#define IDB_LIUJIAO_1A                  233
#define IDB_LIUJIAO_1BMASK              234
#define IDB_LIUJIAO_1B                  235
#define IDB_LIUJIAO_1CMASK              236
#define IDB_LIUJIAO_1C                  237
#define IDB_LIUJIAO_1DMASK              238
#define IDB_LIUJIAO_1D                  239
#define IDB_LIUJIAO_2AMASK              240
#define IDB_LIUJIAO_2A                  241
#define IDB_LIUJIAO_2BMASK              242
#define IDB_LIUJIAO_2B                  243
#define IDB_LIUJIAO_2CMASK              244
#define IDB_LIUJIAO_2C                  245
#define IDB_LIUJIAO_2DMASK              246
#define IDB_LIUJIAO_2D                  247
#define IDB_LIUJIAO_3AMASK              248
#define IDB_LIUJIAO_3A                  249
#define IDB_LIUJIAO_3BMASK              250
#define IDB_LIUJIAO_3B                  251
#define IDB_LIUJIAO_3CMASK              252
#define IDB_LIUJIAO_3C                  253
#define IDB_LIUJIAO_3DMASK              254
#define IDB_LIUJIAO_3D                  255
#define IDB_LIUJIAO_4AMASK              256
#define IDB_LIUJIAO_4A                  257
#define IDB_LIUJIAO_4BMASK              258
#define IDB_LIUJIAO_4B                  259
#define IDB_LIUJIAO_4CMASK              260
#define IDB_LIUJIAO_4C                  261
#define IDB_LIUJIAO_4DMASK              262
#define IDB_LIUJIAO_4D                  263
#define IDB_SERAPHINA_1AMASK            264
#define IDB_SERAPHINA_1A                265
#define IDB_SERAPHINA_1BMASK            266
#define IDB_SERAPHINA_1B                267
#define IDB_SERAPHINA_1CMASK            268
#define IDB_SERAPHINA_1C                269
#define IDB_SERAPHINA_1DMASK            270
#define IDB_SERAPHINA_1D                271
#define IDB_SERAPHINA_2AMASK            272
#define IDB_SERAPHINA_2A                273
#define IDB_SERAPHINA_2BMASK            274
#define IDB_SERAPHINA_2B                275
#define IDB_SERAPHINA_2CMASK            276
#define IDB_SERAPHINA_2C                277
#define IDB_SERAPHINA_2DMASK            278
#define IDB_SERAPHINA_2D                279
#define IDB_SERAPHINA_3AMASK            280
#define IDB_SERAPHINA_3A                281
#define IDB_SERAPHINA_3BMASK            282
#define IDB_SERAPHINA_3B                283
#define IDB_SERAPHINA_3CMASK            284
#define IDB_SERAPHINA_3C                285
#define IDB_SERAPHINA_3DMASK            286
#define IDB_SERAPHINA_3D                287
#define IDB_SERAPHINA_4AMASK            288
#define IDB_SERAPHINA_4A                289
#define IDB_SERAPHINA_4BMASK            290
#define IDB_SERAPHINA_4B                291
#define IDB_SERAPHINA_4CMASK            292
#define IDB_SERAPHINA_4C                293
#define IDB_SERAPHINA_4DMASK            294
#define IDB_SERAPHINA_4D                295
#define IDB_DIMITRI_W1MASK              303
#define IDB_DIMITRI_W1                  304
#define IDB_DIMITRI_W2                  305
#define IDB_DIMITRI_W3                  306
#define IDB_DIMITRI_W4                  307
#define IDB_DIMITRI_W5                  308
#define IDB_DIMITRI_W6                  309
#define IDB_DIMITRI_W7                  310
#define IDB_DIMITRI_W8                  311
#define IDB_DIMITRI_W9                  312
#define IDB_DIMITRI_W10                 313
#define IDB_LIUJIAO_E1MASK              314
#define IDB_LIUJIAO_E1                  315
#define IDB_LIUJIAO_R1MASK              322
#define IDB_LIUJIAO_R1                  323
#define IDB_LIUJIAO_R2                  324
#define IDB_LIUJIAO_R3MASK              325
#define IDB_LIUJIAO_R3                  326
#define IDB_QUATTRO_E1MASK              327
#define IDB_QUATTRO_E1                  328
#define IDB_QUATTRO_Q1MASK              329
#define IDB_QUATTRO_Q1                  330
#define IDB_QUATTRO_Q2                  331
#define IDB_QUATTRO_Q3                  332
#define IDB_QUATTRO_Q4                  333
#define IDB_QUATTRO_Q5                  334
#define IDB_QUATTRO_Q6                  335
#define IDB_QUATTRO_Q7MASK              336
#define IDB_QUATTRO_Q7                  337
#define IDB_QUATTRO_Q8                  338
#define IDB_QUATTRO_Q9                  339
#define IDB_QUATTRO_R1MASK              340
#define IDB_QUATTRO_R1                  341
#define IDB_QUATTRO_R2                  342
#define IDB_QUATTRO_R3                  343
#define IDB_QUATTRO_R4                  344
#define IDB_QUATTRO_W1MASK              345
#define IDB_QUATTRO_W1                  346
#define IDB_SERAPHINA_E1MASK            347
#define IDB_SERAPHINA_E1                348
#define IDB_SERAPHINA_Q1MASK            349
#define IDB_SERAPHINA_Q1                350
#define IDB_SERAPHINA_Q2                351
#define IDB_SERAPHINA_Q3                352
#define IDB_SERAPHINA_Q4                353
#define IDB_SERAPHINA_Q5                354
#define IDB_SERAPHINA_R1MASK            355
#define IDB_SERAPHINA_R1                356
#define IDB_SERAPHINA_W1MASK            357
#define IDB_SERAPHINA_W1                358
#define IDB_SERAPHINA_W2                359
#define IDB_COOLDOWN_01                 360
#define IDB_COOLDOWN_02                 361
#define IDB_COOLDOWN_03                 362
#define IDB_COOLDOWN_04                 363
#define IDB_COOLDOWN_05                 364
#define IDB_COOLDOWN_06                 365
#define IDB_COOLDOWN_07                 366
#define IDB_COOLDOWN_08                 367
#define IDB_COOLDOWN_09                 368
#define IDB_COOLDOWN_10                 369
#define IDB_COOLDOWN_11                 370
#define IDB_COOLDOWN_12                 371
#define IDB_COOLDOWN_13                 372
#define IDB_COOLDOWN_14                 373
#define IDB_COOLDOWN_15                 374
#define IDB_COOLDOWN_16                 375
#define IDB_COOLDOWN_17                 376
#define IDB_COOLDOWN_18                 377
#define IDB_COOLDOWN_19                 378
#define IDB_COOLDOWN_20                 379
#define IDB_COOLDOWN_MASK               380
#define IDB_COUNTER_1MASK               381
#define IDB_COUNTER_1                   382
#define IDB_COUNTER_2MASK               383
#define IDB_COUNTER_2                   384
#define IDB_COUNTER_3MASK               385
#define IDB_COUNTER_3                   386
#define IDB_QUATTRO_W2MASK              387
#define IDB_QUATTRO_W2                  388
#define IDB_QUATTRO_W3                  389
#define IDB_QUATTRO_W4                  390
#define IDB_DIMITRI_E1MASK              391
#define IDB_DIMITRI_E1                  392
#define IDB_DIMITRI_E2MASK              393
#define IDB_DIMITRI_E2                  394
#define IDB_DIMITRI_Q1MASK              395
#define IDB_DIMITRI_Q1                  396
#define IDB_DIMITRI_Q2MASK              397
#define IDB_DIMITRI_Q2                  398
#define IDB_DIMITRI_Q3MASK              399
#define IDB_DIMITRI_Q3                  400
#define IDB_DIMITRI_W11MASK             401
#define IDB_DIMITRI_W11                 402
#define IDB_LIUJIAO_Q1MASK              403
#define IDB_LIUJIAO_Q2                  405
#define IDB_LIUJIAO_Q1                  407
#define IDB_LIUJIAO_Q3                  408
#define IDB_SLTSCREEN                   410
#define IDB_STR_EXIT                    425
#define IDB_STR_PLAYMASK                426
#define IDB_STR_PLAY                    427
#define IDB_STRSCREEN                   428
#define IDB_STR_TITLEMASK               429
#define IDB_STR_TITLE                   430
#define IDD_LEVELBOX                    431
#define IDD_MATCHBOX                    433
#define IDD_RESULTBOX                   435
#define IDB_WINNER_1                    441
#define IDB_WINNER_2                    442
#define IDB_WINNER_4                    444
#define IDB_WINNER_5                    445
#define IDB_WINNER_MASK                 446
#define IDB_WINNER_3                    447
#define IDB_ANNOUNCE_1MASK              448
#define IDB_ANNOUNCE_1                  449
#define IDB_ANNOUNCE_2                  450
#define IDB_ANNOUNCE_3                  451
#define IDB_ANNOUNCE_4                  452
#define IDB_ANNOUNCE_5                  453
#define IDB_ANNOUNCE_6MASK              454
#define IDB_ANNOUNCE_6                  456
#define IDB_PRACTICE_SIGNMASK           457
#define IDB_PRACTICE_SIGN               458
#define IDB_SLT_SIGNMASK                460
#define IDB_SLT_SIGN                    461
#define IDD_ABOUT_PLAY                  462
#define IDB_ABOUT_DIMITRI               465
#define IDB_ABOUT_LIUJIAO               466
#define IDD_ABOUT_QUATTRO               471
#define IDD_ABOUT_SERAPHINA             473
#define IDD_ABOUT_DIMITRI               475
#define IDD_ABOUT_LIUJIAO               478
#define IDD_ABOUT_CREDITS               480
#define IDB_ABOUT_SERAPHINA             484
#define IDB_ABOUT_QUATTRO               485
#define IDB_ABOUT_PLAY                  486
#define IDB_BITMAP1                     488
#define IDB_ABOUT_CREDITS               488
#define ID_MODEBOX_BACK                 1001
#define ID_MODEBOX_OK                   1004
#define IDC_MODEBOX_TEXT2               1005
#define IDC_MODEBOX_TEXT3               1006
#define IDC_MODEBOX_TEXT1               1007
#define IDC_MODEBOX_TEXT4               1008
#define IDC_MODEBOX_TEXT5               1009
#define IDC_CHALLENGERMODE              1019
#define IDC_QUICKMODE                   1020
#define IDC_PRACTICEMODE                1021
#define IDC_EASYLEVEL                   1022
#define IDC_HARDLEVEL                   1023
#define ID_LEVELBOX_OK                  1024
#define ID_LEVELBOX_BACK                1025
#define ID_MATCHBOX_BACK                1025
#define IDC_PLAYER1                     1026
#define IDC_PLAYER2                     1027
#define IDC_MATCHBOX_TEXT1              1028
#define IDC_MATCHBOX_TEXT2              1029
#define IDC_MATCHBOX_TEXT3              1030
#define IDC_MATCHBOX_TEXT4              1031
#define ID_MATCHBOX_OK                  1032
#define ID_RESULT_PLAYBUTTON            1033
#define ID_RESULT_QUITBUTTON            1034
#define IDC_RESULT_TEXT                 1035
#define IDC_ABOUT_DIMITRI               1043
#define IDC_ABOUT_LIUJIAO               1044
#define IDC_ABOUT_CREDITS               1045
#define IDC_ABOUT_SERAPHINA             1048
#define IDC_ABOUT_QUATTRO               1049
#define IDC_ABOUT_PLAY                  1050
#define ID_FILE_EXIT                    40001
#define ID_ABOUT_HOWTOPLAY              40002
#define ID_ABOUT_CONTROLS               40003
#define ID_CONTROLS_QUATTRO             40004
#define ID_SOUND_ON                     40005
#define ID_SOUND_OFF                    40006
#define ID_FILE_EXIT40007               40007
#define ID_FILE_RETURN                  40008
#define ID_FILE_SRTSCREEN               40009
#define ID_FILE_STRSCREEN               40011
#define ID_ABOUT_CREDITS                40012
#define ID_CONTROLS_QUATTRO40013        40013
#define ID_CONTROLS_SERAPHINA           40014
#define ID_CONTROLS_DIMITRI             40015
#define ID_CONTROLS_LIUJIAO             40016
#define ID_ABOUT_MOVESETS               40017
#define ID_ABOUT_MOVESET                40018
#define ID_MOVESET_QUATTRO              40019
#define ID_MOVESET_SERAPHINA            40020
#define ID_MOVESET_DIMITRI              40021
#define ID_MOVESET_LIUJIAO              40022

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        489
#define _APS_NEXT_COMMAND_VALUE         40023
#define _APS_NEXT_CONTROL_VALUE         1051
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
